language: node_js
node_js:
  - "8.0.0"
install:
  - npm install
services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm test
branches:
  only:
  - heroku-deploy
env:
  -TOKEN_SECRET