language: node_js
node_js:
    - "6.11.0"
install:
    - npm install
before_script:
  - createuser chuks -s -U postgres
  - createdb postit_dev --username=chuks
  - sequelize db:migrate
script:
    - npm test
services:
  - postgresql