
sudo: required
dist: trusty
language: node_js
node_js: "8"
script:
  - npm test
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres
after_success: 
 - npm run coverage