export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_GROUP_DETAILS = 'SET_GROUP_DETAILS';
export const PASS_MESSAGE = 'PASS_MESSAGE';
export const GET_USER_GROUPS = 'GET_USER_GROUPS';
